/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sala2;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gg
 */
public class Computers extends javax.swing.JFrame {
 private DefaultTableModel compu_table;
 public int number, row,available;
 String so="";

    /**
     * Creates new form Computadoras
     */
    public Computers() {
        initComponents();
    mostrarlista();
    }

    
    public void mostrarlista() {
        Query request = new Query();
        Conexion_DB con = new Conexion_DB();
        String SQLQuery = "";
        
            SQLQuery = "SELECT * from computadora  ";
        
       

        ResultSet rs = request.executeQuery(SQLQuery, con);
        try {
            String titulos[] = {"Numero", "Fila", "Disponible", "Sistema Operativo"};
            String datos[] = new String[4];

            compu_table = new DefaultTableModel(null, titulos);

            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(3);
                datos[2] = disponible(rs.getInt(2));
                datos[3] = rs.getString(4);

                compu_table.addRow(datos);
            }
            view.setModel(compu_table);
            view.addMouseListener(new MouseAdapter() {

                     public void mouseClicked(MouseEvent me){
                         if(SwingUtilities.isRightMouseButton(me)){
                         
                         ppm_compus.show(view,me.getX(),me.getY());
                         
                         }
                     }   
                    });
            return;
        } catch (Exception e) {
        } finally {
            con = null;
        }
    }
    
    
    public String disponible(int num){
    if(num==0)
        return "Si";
                else
        return "No";
    }
    
     
       public int disponible(String num){
    if(num.equals("Si"))
        return 0;
                else
        return 1;
    }
    
      public String so(String num){
    if(num.startsWith("w"))
        return "Windows";
    else if(num.startsWith("W"))
        return "Windows";
    else if(num.startsWith("m"))
        return "Mac";
    else 
        return "Mac";
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ppm_compus = new javax.swing.JPopupMenu();
        Editar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        delete = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        view = new javax.swing.JTable();
        add = new javax.swing.JButton();
        buscar_compu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        ppm_compus.add(Editar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        ppm_compus.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Computadoras");
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(java.awt.Color.cyan);

        delete.setText("Eliminar Computadora");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        edit.setText("Editar  Computadora ");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Fila", "Disponible", "S.O."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(view);

        add.setText("Agregar Computadora");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        buscar_compu.setText("Aun no hace nada");
        buscar_compu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_compuActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar_compu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscar_compu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete)
                    .addComponent(edit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        Query request = new Query();


number= Integer.parseInt(compu_table.getValueAt(view.getSelectedRow(),0).toString());
JOptionPane.showMessageDialog(null,number);


        Conexion_DB con = new Conexion_DB();
        String SQLQuery = "";

            SQLQuery = "DELETE from computadora WHERE Id= "+number;
   boolean delete= request.execute(SQLQuery);
   if(delete){
       JOptionPane.showMessageDialog(null,"computadora eliminada ");
   }
   mostrarlista();
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
Query request = new Query();
number=Integer.parseInt(JOptionPane.showInputDialog(null," Numero de Equipo?"));
row=Integer.parseInt(JOptionPane.showInputDialog(null," Fila 1 ó 2"));
available=0;
so=so(JOptionPane.showInputDialog(null," Windows ó Mac"));


     
        Conexion_DB con = new Conexion_DB();
        String SQLQuery = "";
        
       
        
        
            SQLQuery = "INSERT INTO computadora ( `Id`, `Fila`, `Disponible`, `SO`) VALUES ( '"+number+"' , '"+ row +"', '"+ available +"', '"+so+"') ";
   boolean add= request.execute(SQLQuery);
   if(add){
       Menu op =new Menu();
       op.showcomputers();
   }
   mostrarlista();
   
   
           }//GEN-LAST:event_addActionPerformed

    private void buscar_compuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_compuActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_buscar_compuActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
         Query request = new Query();


this.number= Integer.parseInt(compu_table.getValueAt(view.getSelectedRow(),0).toString());
JOptionPane.showMessageDialog(null,number);
row=Integer.parseInt(compu_table.getValueAt(view.getSelectedRow(),1).toString());
available=disponible(compu_table.getValueAt(view.getSelectedRow(),2).toString());
so=so(compu_table.getValueAt(view.getSelectedRow(),3).toString());



        Conexion_DB con = new Conexion_DB();
        String SQLQuery = "";

            SQLQuery = "Update computadora set Fila ="+row+",Disponible ="+available+",SO ="+so+" WHERE Id= "+number;
   boolean update= request.execute(SQLQuery);
   if(update){
       JOptionPane.showMessageDialog(null,"Modificación Agregada, Reinicie Sistema Para Mostrar Cambios ");
   }
   mostrarlista();
    }//GEN-LAST:event_editActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        editActionPerformed( evt);
    }//GEN-LAST:event_EditarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
     deleteActionPerformed(evt);
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Computers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Computers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Computers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Computers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Computers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Editar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JButton add;
    private javax.swing.JTextField buscar_compu;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu ppm_compus;
    private javax.swing.JTable view;
    // End of variables declaration//GEN-END:variables
}
